1. 배열 생성

In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

2. 배열 정보 보기

In [2]:
print('type  : ', type(a))
print('ndim  : ', a.ndim)
print('shape : ', a.shape)
print('dtype : ', a.dtype)

type  :  <class 'numpy.ndarray'>
ndim  :  2
shape :  (2, 2)
dtype :  int32


In [3]:
print('max  : ', a.max())
print('mean : ', a.mean())
print('min  : ', a.min())
print('sum  : ', a.sum())

max  :  4
mean :  2.5
min  :  1
sum  :  10


3. 배열의 접근

In [4]:
print(a[0])
print(a[1])

[1 2]
[3 4]


In [5]:
print(a[0][0],a[0][1])
print(a[1][0],a[1][1])

1 2
3 4


4. 배열의 형태 바꾸기

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
a.T # == a.transpose()

array([[1, 3],
       [2, 4]])

In [8]:
a.flatten()

array([1, 2, 3, 4])

6. 브로드캐스팅

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
b = np.array([10,100])

In [11]:
a * b

array([[ 10, 200],
       [ 30, 400]])

7. 내적 구하기

In [12]:
b.dot(b) # (10 x 10 + 100 x 100) = 10100

10100

In [13]:
a.dot(b)

array([210, 430])

In [1]:
from IPython.core.display import display, HTML

display(HTML("<style> .container{width:90% !important;}</style>"))